analysis/urls.py
from django.urls import path
from . import views

app_name = "analysis"

urlpatterns = [
    path('', views.SearchView.as_view(),name="index"),
    path('result/', views.DisplayView.as_view(),name="result"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("analysis.urls")),
]

analysis/models.py
from django.db import models

# class Pv(models.Model):
#     nama = models.CharField("ページ名",max_length=30)
#     page_view = models.BigAutoField("ページビュー")

analysis/views.py
from django.shortcuts import render
from django.views import generic

import requests
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
import datetime

class SearchView(generic.TemplateView):
    template_name = "analysis/form.html"


class DisplayView(generic.TemplateView):
    template_name = "analysis/result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search1"] = self.request.GET.get("search1")
        context["search2"] = self.request.GET.get("search2")
        context["search3"] = self.request.GET.get("search3")
        context["start"] = self.request.GET.get("start")
        context["end"] = self.request.GET.get("end")

        key1 = self.request.GET.get("search1")
        key2 = self.request.GET.get("search2")
        key3 = self.request.GET.get("search3")

        start_year = self.request.GET.get("start_year")
        start_month = self.request.GET.get("start_month")
        start_day = self.request.GET.get("start_day")
        end_year = self.request.GET.get("end_year")
        end_month = self.request.GET.get("end_month")
        end_day = self.request.GET.get("end_day")

        if len(start_month) == 1:
            start_month = "0"+start_month
        if len(start_day) == 1:
            start_day = "0"+start_day
        if len(end_month) == 1:
            end_month = "0"+end_month
        if len(end_day) == 1:
            end_day = "0"+end_day


        start = start_year+start_month+start_day
        end = end_year+end_month+end_day

        view_lsit_lsit = []
        for key in [key1,key2,key3]:
            url = f"https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/user/{key}/daily/{start}/{end}"
            r = requests.get(url)
            print(url)

            date_list = []
            view_list = []
            for k in range(len(r.json()["items"])):
                date_list.append(r.json()["items"][k]["timestamp"])
                view_list.append(r.json()["items"][k]["views"])
            view_lsit_lsit.append(view_list)

        # context["search_result_date"] = [datetime.datetime.strptime(s,'%Y%m%d%H') for s in date_list]
        context["search_result_date"] = [int(s) for s in date_list]
        context["search_result_view"] = view_lsit_lsit

        return context

analysis/templates/analysis/form.html
{% extends "base.html" %}

{% block body %}
<!-- <form action="{% url 'analysis:result' %}" method="GET"> -->


{% endblock %}

analysis/templates/analysis/result.html
{% extends "base.html" %}

{% block body %}

<br>

<canvas id="mycanvas" height="400" width="1000" class="mb-5"></canvas>

<!-- {% for view in search_result_view %}
  <p>{{ view }}</p>
{% endfor %} -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

<script type="text/javascript">
  var view = {}
  i=1
  {% for view in search_result_view %}
    view[i] = {{ view }};
    i += 1
  {% endfor %}

  var ctx = document.getElementById("mycanvas");
  var myChart = new Chart(ctx, {
      type: 'line',
      data: {
          labels: {{search_result_date}},
          datasets: [{
                          label: '{{ search1 }}',
                          data: view[1],
                          borderColor: "rgba(100,220,220,1)",
                          pointHoverRadius: 5,
                          pointHitRadius: 15,
                      },
                      {% if search2 %}
                      {
                          label: '{{ search2 }}',
                          data: view[2],
                          borderColor: "rgba(220,100,220,1)",
                          pointHoverRadius: 5,
                          pointHitRadius: 15,
                      },
                      {% endif %}
                      {% if search3 %}
                      {
                          label: '{{ search3 }}',
                          data: view[3],
                          borderColor: "rgba(220,220,100,1)",
                          pointHoverRadius: 5,
                          pointHitRadius: 15,
                      },
                      {% endif %}
          ],


      },
  });
</script>

{% endblock %}

analysis/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Wiki分析ツール</title>
  </head>
  <body>

    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-3">Wiki分析ツール</h1>
        <p class="lead">研究をより簡単に！</p>
        <p style="color:gray">Created by gakuto.</p>
      </div>
    </div>
    <div class="container">

      <form action="{% url 'analysis:result' %}" method="GET" id="">
        <div id="input">
          <input type="search" name="search1" placeholder="キーワードを入力">
        </div>
        <p class="btn btn-primary mt-2" id="add_btn"">キーワード追加</p><br>
          <select name="start_year">
            <option value="">-</option>
            <option value="2013">2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019" selected>2019</option>
          </select> 年

          <select name="start_month">
            <option value="">-</option>
            <option value="1"selected>1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
          </select> 月

          <select name="start_day">
            <option value="">-</option>
            <option value="1" selected>1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
            <option value="21">21</option>
            <option value="22">22</option>
            <option value="23">23</option>
            <option value="24">24</option>
            <option value="25">25</option>
            <option value="26">26</option>
            <option value="27">27</option>
            <option value="28">28</option>
            <option value="29">29</option>
            <option value="30">30</option>
            <option value="31">31</option>
          </select> 日から
          <select name="end_year">
                <option value="">-</option>
                <option value="2013">2013</option>
                <option value="2014">2014</option>
                <option value="2015">2015</option>
                <option value="2016">2016</option>
                <option value="2017">2017</option>
                <option value="2018">2018</option>
                <option value="2019" selected>2019</option>
              </select> 年

              <select name="end_month">
                <option value="">-</option>
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
              </select> 月

              <select name="end_day">
                <option value="">-</option>
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
                <option value="19">19</option>
                <option value="20">20</option>
                <option value="21">21</option>
                <option value="22">22</option>
                <option value="23">23</option>
                <option value="24">24</option>
                <option value="25">25</option>
                <option value="26">26</option>
                <option value="27">27</option>
                <option value="28">28</option>
                <option value="29">29</option>
                <option value="30">30</option>
                <option value="31">31</option>
              </select> 日
      <button type="submit" class="btn btn-primary">検索</button>
      <hr>
    </form>
      {% block body %}
      {% endblock%}
    </div>

    <script type="text/javascript">


      var add_btn = document.getElementById("add_btn");

      add_btn.addEventListener('click',function(){
        var parent = document.getElementById('input');
        num_child = parent.childElementCount + 1;

        var new_input = document.createElement('input');
        new_input.setAttribute("type","search");
        new_input.setAttribute("name","search"+num_child);
        new_input.setAttribute("placeholder","キーワードを入力");

        parent.appendChild(new_input);
      });

    </script>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block extrajs %}
    {% endblock%}
  </body>
</html>